= Cross-Testing Feedback

__Durchführende Gruppe:__  18 
__Anwendung von Gruppe:__  17

== Getestetes System
Welche Aufgabe/Problemstellung löst die Anwendung. +
Die Anwendung löst die Aufgabenstellung zur Erstellung einer Spring- und Salespointanwendung für die Tankstelle "McTank". Darin sind die Basisfunktionalitäten wie z.B. die Kasse, Reservierungen, Useraccount-Erstellung und Verwaltung, Inventar und Bestellungen implementiert.

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| … | … | … | … |
|===

- Fehler beim Klick auf Kasse "template "Kasse" might not exist or might not be accessible"

== Sonstiges
* Optik der Anwendung
- übersichtlich
- einfach zu bedienen
* Fehlende Features
* Interaktion mit der Anwendung (Usability)
- nach löschen von Mitarbeiter/Manager/Customer immer redirect zu /customers
- Klick auf Username immer Error
- bei Items bearbeiten: Fehlende Einträge werden nicht abgefangen -> redirect zu Errorpage 
- bei Items bearbeiten: leere Namen werden aktzeptiert -> Produkte ohne Name möglich

== Verbesserungsvorschläge
* Was kann noch weiter verbessert werden?
