= Zeiterfassung für Gruppe 18

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |David L |Vivien |Christoph |Artem |Clemens |Meeting
|1  |300   |360    |180    |180    |300    |0    
|2  |360   |240    |120    |120    |240    |90
|3  |480   |360    |270    |240    |570    |90    
|4  |300   |180    |240    |300    |60     |90
|5  |480   |480    |420    |400    |630    |90
|6  |360   |360    |420    |2880   |360    |45
|7  |390   |840    |375    |400    |450    |90
|8  |300   |300    |300    |2700   |…   |90
|9  |1080  |840    |…    |…    |…   |90   
|10  |…   |…    |…    |…    |…   |45    
|11  |…   |…    |…    |…    |…   |…    
|12  |…   |…    |…    |…    |…   |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
